apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../qa

images:
  - name: docker.io/charlires/goapp
    newTag: 1.0.0
# patchesStrategicMerge:
#   - deployment.yml
#   - service.yml

# configMapGenerator:
#   - name: demo-app-config
#     behavior: merge
#     files:
#       - config.yml
