apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
