apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 8081
    - name: http
      port: 80
      targetPort: 8081
    - nodePort: 30000
      port: 8081
      targetPort: 8081
      $patch: delete
