name: Code Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Code Integration
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Test
        run: go test -v -covermode=count ./...

      - name: Lint
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: false

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Docker Build and Push
        uses: docker/build-push-action@v1
        with:
          username: charlires
          password: ${{secrets.GITHUB_TOKEN}}
          repository: charlires/go-app/api
          registry: docker.pkg.github.com
          tag_with_sha: true
          # tag_with_ref: true

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.1.0"

      - name: Generate Kubernetes Deployment file
        run: |
          mkdir ./k8s/out
          kustomize build ./k8s/base > ./k8s/out/base.yml

      - name: Upload Kubernetes Deployment file
        uses: actions/upload-artifact@v1
        with:
          name: kubernetes.yml
          path: ./k8s/out/base.yml
