name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      # - name: Build
      #   run: go build -v .

      - name: Test
        run: go test -v .

      - name: Build Docker Image
        run: docker build -t charlires/go-app .

      - name: Login Docker Hub
        with:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: docker login -u charlires --password-stdin

      - name: Push Docker Image
        run: docker push charlires/go-app
